"""
Django settings for djangoflix project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-usc$50%r09^xhp+15ozy-e94*txjx#$40hmf%1zkh!#rq8k0#0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filme',  # Adicionando a aplicação filme
    'crispy_forms',  # Adiciona o pacote crispy_forms para estilização de formulários do Django
    'crispy_bootstrap5',  # Adiciona o pacote crispy_forms com o tema Bootstrap 5 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Permite servir arquivos estáticos em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoflix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  # Informa a existência do diretório templates na estrutura do projeto principal
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'filme.new_context.lista_filmes_recentes',  # Adiciona a função lista_filmes_recentes ao contexto
                'filme.new_context.lista_filmes_emalta',  # Adiciona a função lista_filmes_emalta ao contexto
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoflix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

import dj_database_url
import os

DATABASE_URL = os.getenv('DATABASE_URL')  # Obtém a URL do banco de dados do ambiente

# Se DATABASE_URL estiver vazia, configura o banco de dados usando dj_database_url
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'filme.Usuario' # Informa ao sistema quem é o modelo responsável pelo controle de usuários (aplicativo.modelo)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' # Default is 'en-us'

TIME_ZONE = 'America/Sao_Paulo' # Default is 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'  # Pasta onde os arquivos estáticos serão coletados em produção

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Pasta onde as imagens serão armazenadas


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configurações de redirecionamento de usuários não logados ao site
LOGIN_REDIRECT_URL = 'filme:homefilmes'  # URL para onde o usuário será redirecionado ao fazer login
LOGIN_URL = 'filme:login'  # URL para a página de login

# Constantes do Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # Permite o uso do tema Bootstrap 5
CRISPY_TEMPLATE_PACK = "bootstrap5"  # Define o tema Bootstrap 5 como padrão para os formulários